var json = {
	"information1": {
		"restaurants": ["Restaurants:", "Chilli's"],
		"groceries": ["Groceries Stores:", "Publix"],
		"fastFood": ["Fast Food:", "McDonalds"],
		"department": ["Department Stores:", "Macys"],
		"clothing": ["Clothing Stores:", "Ross"],
	},
	"information2": {
		"restaurants": ["Restaurants:", "Applebee's"],
		"groceries": ["Groceries Stores:", "Winn Dixie"],
		"fastFood": ["Fast Food:", "Wendy's"],
		"department": ["Department Stores:", "Jc Pennys"],
		"clothing": ["Clothing Stores:", "Marshalls"],
	},
	"information3": {
		"restaurants": ["Restaurants:", "Carrabas"],
		"groceries": ["Groceries Stores:", "Albertsons"],
		"fastFood": ["Fast Food:", "Burger King"],
		"department": ["Department Stores:", "Target"],
		"clothing": ["Clothing Stores:", "T.J Maxx"],
	},
	"information4": {
		"restaurants": ["Restaurants:", "Ruby Tuesdays"],
		"groceries": ["Groceries Stores:", "Kash & Karry"],
		"fastFood": ["Fast Food:", "Red Robins"],
		"department": ["Department Stores:", "Dillards"],
		"clothing": ["Clothing Stores:", "Hollister"],
	},
	"information5": {
		"restaurants": ["Restaurants:", "Outback"],
		"groceries": ["Groceries Stores:", "Piglie Wigglie"],
		"fastFood": ["Fast Food:", "Checkers"],
		"department": ["Department Stores:", "Khols"],
		"clothing": ["Clothing Stores:", "Aeropostal"],
	},
	"information6": {
		"restaurants": ["Restaurants:", "J alexanders"],
		"groceries": ["Groceries Stores:", "Smiths"],
		"fastFood": ["Fast Food:", "Chick fil A"],
		"department": ["Department Stores:", "Nordstrums"],
		"clothing": ["Clothing Stores:", "Pac Sun"],
	},
	"information7": {
		"restaurants": ["Restaurants:", "P.J Changs"],
		"groceries": ["Groceries Stores:", "Jewl Osco"],
		"fastFood": ["Fast Food:", "Sonic"],
		"department": ["Department Stores:", "Woolworth"],
		"clothing": ["Clothing Stores:", "Tillys"],
	},
	"information8": {
		"restaurants": ["Restaurants:", "Cheesecake Factory"],
		"groceries": ["Groceries Stores:", "Dominics"],
		"fastFood": ["Fast Food:", "Taco Bell"],
		"department": ["Department Stores:", "Montgomery Wards"],
		"clothing": ["Clothing Stores:", "Forevery 21"],
	},
	"information9": {
		"restaurants": ["Restaurants:", "Mimi's Cafe"],
		"groceries": ["Groceries Stores:", "Aldi"],
		"fastFood": ["Fast Food:", "Del Taco"],
		"department": ["Department Stores:", "Beth Bath & Beyond"],
		"clothing": ["Clothing Stores:", "The Gap"],
	},
	"information10": {
		"restaurants": ["Restaurants:", "Olive Garden"],
		"groceries": ["Groceries Stores:", "Bravo"],
		"fastFood": ["Fast Food:", "Churche's"],
		"department": ["Department Stores:", "Bells"],
		"clothing": ["Clothing Stores:", "Ann Taylors"],
	},
	"information11": {
		"restaurants": ["Restaurants:", "Red Lobster"],
		"groceries": ["Groceries Stores:", "Goodings"],
		"fastFood": ["Fast Food:", "KFC"],
		"department": ["Department Stores:", "Sears"],
		"clothing": ["Clothing Stores:", "Wet Seal"],
	},
	"information12": {
		"restaurants": ["Restaurants:", "Smokey Bones"],
		"groceries": ["Groceries Stores:", "Food Lion"],
		"fastFood": ["Fast Food:", "Arbys"],
		"department": ["Department Stores:", "K-Mart"],
		"clothing": ["Clothing Stores:", "Express"],
	},
	"information13": {
		"restaurants": ["Restaurants:", "Ruth Chrises"],
		"groceries": ["Groceries Stores:", "Save a Lot"],
		"fastFood": ["Fast Food:", "Steak & Shake"],
		"department": ["Department Stores:", "Lord & Taylor"],
		"clothing": ["Clothing Stores:", "Old Navy"],
	},
	"information14": {
		"restaurants": ["Restaurants:", "Long Horns"],
		"groceries": ["Groceries Stores:", "Cosco"],
		"fastFood": ["Fast Food:", "Pollo Tropical"],
		"department": ["Department Stores:", "Barneys"],
		"clothing": ["Clothing Stores:", "Rue 21"],
	},
	"information15": {
		"restaurants": ["Restaurants:", "Texas Roadhouse"],
		"groceries": ["Groceries Stores:", "Sams"],
		"fastFood": ["Fast Food:", "Long John Silver"],
		"department": ["Department Stores:", "Belk"],
		"clothing": ["Clothing Stores:", "Charlotte Russe"],
	},
	"information16": {
		"restaurants": ["Restaurants:", "Bonefish Willies"],
		"groceries": ["Groceries Stores:", "Kroger"],
		"fastFood": ["Fast Food:", "Moe's"],
		"department": ["Department Stores:", "Bloomingdales"],
		"clothing": ["Clothing Stores:", "Fashion Bug"],
	},
	"information17": {
		"restaurants": ["Restaurants:", "Chipoltle"],
		"groceries": ["Groceries Stores:", "Food for less"],
		"fastFood": ["Fast Food:", "Whattaburger"],
		"department": ["Department Stores:", "Saks 5th Ave"],
		"clothing": ["Clothing Stores:", "Big & Tall"],
	},
	"information18": {
		"restaurants": ["Restaurants:", "Conky Joes"],
		"groceries": ["Groceries Stores:", "Hyvee"],
		"fastFood": ["Fast Food:", "Hardees"],
		"department": ["Department Stores:", "Neiman Marcus"],
		"clothing": ["Clothing Stores:", "Mens Warehouse"],
	},
	"information19": {
		"restaurants": ["Restaurants:", "Charley & Jake"],
		"groceries": ["Groceries Stores:", "Market Basket"],
		"fastFood": ["Fast Food:", "Carls Jr"],
		"department": ["Department Stores:", "Hudsons"],
		"clothing": ["Clothing Stores:", "American Eagle Outfitters"],
	},
	"information20": {
		"restaurants": ["Restaurants:", "Buffalo Wild Wings"],
		"groceries": ["Groceries Stores:", "Fareway"],
		"fastFood": ["Fast Food:", "Subway"],
		"department": ["Department Stores:", "Burdines"],
		"clothing": ["Clothing Stores:", "The Body Shop"],
		
	}
}